services:
  backend:
    image: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file: 
      - ./backend/.env
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - internal_net
      - data_net


  processor:
    image: processor
    build:
      context: ./processor
      dockerfile: Dockerfile
    env_file: 
      - ./processor/.env
    ports:
      - 8080:8080
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
    environment:
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: all
    networks:
      - internal_net
    
  db:
    image: postgres:17-alpine3.22
    ports:
      - "5432:5432"
    env_file:
      - ./.env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]      
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - data_net

  redis:
    image: redis:alpine3.22
    restart: always
    ports:
      - "6379:6379"
    env_file: 
      - ./.env
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - redis-data:/data
    networks:
      - data_net

networks:
  internal_net:
    driver: bridge
  data_net:
    driver: bridge

volumes:
  db-data:
  redis-data:
